### ISSUE TITLE
surprising behaviour with cool load

### ISSUE THREAD

**Issue by lldelisle** [deeptools/HiCMatrix#23]
Hi,
I noticed 2 surprising behaviours or at least I think:
1. When a bin has a weight of nan, the weight is transformed to 1 with:
https://github.com/deeptools/HiCMatrix/blob/fa861294296c26e31e877c7c2c2cdfdeda1214ed/hicmatrix/lib/cool.py#L148
But then this bin is not put back in the `nan_bins`.

2. There is a section to rescale matrices which would have a strange range:
https://github.com/deeptools/HiCMatrix/blob/fa861294296c26e31e877c7c2c2cdfdeda1214ed/hicmatrix/lib/cool.py#L198-L199
The problem is that if you load the matrix with `self.chrnameList is None` or with `self.chrnameList is not None`, you may have different outputs... Do you think there could be a parameter which allows to keep the values as they were in the cool file without scaling them?

**Comment by lldelisle** [comment]
Here is an example where 1. is a problem:
![image](https://user-images.githubusercontent.com/30404086/74426571-e5094c80-4e55-11ea-99b5-6cad5e2c0d97.png)
(The cool file was generated by `cooler balance`).

**Comment by aurHin** [comment]
I have this problem, in which the empty diagonals are what you see the most on the plot.

**Comment by aurHin** [comment]
<img width="1184" alt="weirdDiags" src="https://user-images.githubusercontent.com/26483064/75454065-1f560c00-5975-11ea-9263-b0e990d6684e.png">
