### ISSUE TITLE
HiCMatrix installation via conda requires HiCExplorer 2.1.1

### ISSUE THREAD

**Issue by gtrichard** [deeptools/HiCMatrix#3]
So if one installs HiCExplorer 2.1.4 first and then HiCMatrix, he will end up with HiCExplorer 2.1.1. I don't know if it is already known/wanted so I report it here.

**Comment by dpryan79** [comment]
This is due to the `cooler` requirement, which is set to 0.7.11 in HiCMatrix and <=0.7.6 in HiCExplorer. Oone of these will need to be changed in conda.

**Comment by joachimwolff** [comment]
HiCExplorer 2.1.4 is not having any dependency to HiCMatrix, only for HiCExplorer 2.2 it will have one. I fixed this for the development version by setting the version for cooler for both to 0.7.11.
