### ISSUE TITLE
get_chromosome_sizes() on modified matrices

### ISSUE THREAD

**Issue by LeilyR** [deeptools/HiCMatrix#35]
Chromosome size are computed in `get_chromosome_sizes` , taking only the end of the chromosome into account. This is correct for modified matrices and needs to be fixed. https://github.com/deeptools/HiCMatrix/blob/master/hicmatrix/HiCMatrix.py#L963

**Comment by lldelisle** [comment]
I don't know if it is related or not but I also noticed that after doing `maskBins()` the chromosome size change...

**Comment by LeilyR** [comment]
I have not looked for that, but it is good to know, i will check for that too.

**Comment by joachimwolff** [comment]
Implemented in release 15, function get_chromosome_sizes_real
